import { format } from "date-fns"

import { clientDateFormat } from "@/lib/date-utils"

const defaultReceiptDetails = {
  receiptId: "0",
  receiptNo: "",
  itemNo: 0,
  seqNo: 0,
  glId: 0,
  glCode: "",
  glName: "",
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  remarks: "",
  gstId: 0,
  gstName: "",
  gstPercentage: 0,
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  departmentId: 0,
  departmentCode: "",
  departmentName: "",
  employeeId: 0,
  employeeCode: "",
  employeeName: "",
  portId: 0,
  portCode: "",
  portName: "",
  vesselId: 0,
  vesselCode: "",
  vesselName: "",
  bargeId: 0,
  bargeCode: "",
  bargeName: "",
  voyageId: 0,
  voyageNo: "",
  jobOrderId: 0,
  jobOrderNo: "",
  taskId: 0,
  taskName: "",
  serviceId: 0,
  serviceName: "",
  editVersion: 0,
}

const defaultReceipt = {
  companyId: 0,
  receiptId: "0",
  receiptNo: "",
  referenceNo: "",
  trnDate: format(new Date(), clientDateFormat),
  accountDate: format(new Date(), clientDateFormat),
  currencyId: 0,
  currencyCode: null,
  currencyName: null,
  exhRate: 0,
  ctyExhRate: 0,
  paymentTypeId: 0,
  paymentTypeCode: null,
  paymentTypeName: null,
  bankId: 0,
  bankCode: null,
  bankName: null,
  chequeNo: null,
  chequeDate: format(new Date(), clientDateFormat),
  bankChgGLId: 0,
  bankChgAmt: 0,
  bankChgLocalAmt: 0,
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  gstClaimDate: format(new Date(), clientDateFormat),
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  totAmtAftGst: 0,
  totLocalAmtAftGst: 0,
  totCtyAmtAftGst: 0,
  remarks: "",
  payeeTo: "",
  moduleFrom: "",
  createById: 0,
  createDate: format(new Date(), clientDateFormat),
  editById: null,
  editDate: null,
  isCancel: false,
  cancelById: 0,
  cancelDate: null,
  cancelRemarks: null,
  createBy: "",
  editBy: "",
  cancelBy: "",
  editVersion: 0,
  isPost: false,
  postById: null,
  postDate: null,
  appStatusId: null,
  appById: null,
  appDate: null,
  data_details: [],
}

// Function to get default values with custom date format
export const getDefaultValues = (dateFormat: string = clientDateFormat) => {
  return {
    defaultReceipt: {
      ...defaultReceipt,
      trnDate: format(new Date(), dateFormat),
      accountDate: format(new Date(), dateFormat),
      chequeDate: format(new Date(), dateFormat),
      gstClaimDate: format(new Date(), dateFormat),
      createDate: format(new Date(), dateFormat),
    },
    defaultReceiptDetails: {
      ...defaultReceiptDetails,
    },
  }
}

export { defaultReceipt, defaultReceiptDetails }
