import { format } from "date-fns"

import { clientDateFormat } from "@/lib/date-utils"

const defaultBatchPaymentDetails = {
  paymentId: "0",
  paymentNo: "",
  itemNo: 0,
  seqNo: 0,
  invoiceDate: format(new Date(), clientDateFormat),
  invoiceNo: "",
  supplierName: "",
  glId: 0,
  glCode: "",
  glName: "",
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  remarks: "",
  gstId: 0,
  gstName: "",
  gstPercentage: 0,
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  departmentId: 0,
  departmentCode: "",
  departmentName: "",
  employeeId: 0,
  employeeCode: "",
  employeeName: "",
  portId: 0,
  portCode: "",
  portName: "",
  vesselId: 0,
  vesselCode: "",
  vesselName: "",
  bargeId: 0,
  bargeCode: "",
  bargeName: "",
  voyageId: 0,
  voyageNo: "",
  jobOrderId: 0,
  jobOrderNo: "",
  taskId: 0,
  taskName: "",
  serviceId: 0,
  serviceName: "",
  serviceTypeId: 0,
  serviceTypeName: "",
  editVersion: 0,
}

const defaultBatchPayment = {
  companyId: 0,
  paymentId: "0",
  paymentNo: "",
  referenceNo: "",
  trnDate: format(new Date(), clientDateFormat),
  accountDate: format(new Date(), clientDateFormat),
  currencyId: 0,
  exhRate: 0,
  ctyExhRate: 0,
  bankId: 0,
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  gstClaimDate: format(new Date(), clientDateFormat),
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  totAmtAftGst: 0,
  totLocalAmtAftGst: 0,
  totCtyAmtAftGst: 0,
  remarks: "",
  moduleFrom: "",
  createDate: format(new Date(), clientDateFormat),
  editDate: null,
  isCancel: false,
  cancelDate: null,
  cancelRemarks: null,
  createBy: "",
  editBy: "",
  cancelBy: "",
  editVersion: 0,
  isPost: false,
  postDate: null,
  appStatusId: null,
  appById: null,
  appDate: null,
  data_details: [],
}

// Function to get default values with custom date format
export const getDefaultValues = (dateFormat: string = clientDateFormat) => {
  return {
    defaultBatchPayment: {
      ...defaultBatchPayment,
      trnDate: format(new Date(), dateFormat),
      accountDate: format(new Date(), dateFormat),
      gstClaimDate: format(new Date(), dateFormat),
      createDate: format(new Date(), dateFormat),
    },
    defaultBatchPaymentDetails: {
      ...defaultBatchPaymentDetails,
      invoiceDate: format(new Date(), dateFormat),
    },
  }
}

export { defaultBatchPayment, defaultBatchPaymentDetails }
