import { NextRequest, NextResponse } from "next/server"

export async function GET(request: NextRequest) {
  try {
    // Mock data - in real implementation, this would come from database
    const supplierPerformanceData = {
      summary: {
        totalSpend: 8200000,
        totalSuppliers: 6,
        averageScore: 4.1,
        onTimeDelivery: 94.2,
        qualityAcceptance: 96.8,
        invoiceAccuracy: 93.2,
      },
      suppliers: [
        {
          id: "1",
          name: "Premium Materials Ltd",
          spend: 1250000,
          spendPercentage: 15.2,
          onTimeDelivery: 98.5,
          qualityAcceptance: 99.2,
          invoiceAccuracy: 96.8,
          overallScore: 4.8,
          riskRating: "Low",
          category: "Raw Materials",
          location: "North America",
          contractStatus: "Active",
          trend: 5.2,
          relationshipLength: "5 years",
          lastOrderDate: "2024-01-12",
          paymentTerms: "Net 30",
          avgOrderValue: 85000,
          orderFrequency: "Weekly",
          certifications: ["ISO 9001", "ISO 14001"],
          financialHealth: "Strong",
          capacityUtilization: 78,
          priceCompetitiveness: 4.5,
          innovationScore: 4.2,
          sustainabilityScore: 4.6,
        },
        {
          id: "2",
          name: "Global Logistics Inc",
          spend: 980000,
          spendPercentage: 11.9,
          onTimeDelivery: 95.8,
          qualityAcceptance: 97.5,
          invoiceAccuracy: 99.1,
          overallScore: 4.6,
          riskRating: "Low",
          category: "Logistics",
          location: "Global",
          contractStatus: "Active",
          trend: 2.1,
          relationshipLength: "8 years",
          lastOrderDate: "2024-01-10",
          paymentTerms: "Net 15",
          avgOrderValue: 65000,
          orderFrequency: "Daily",
          certifications: ["ISO 9001", "C-TPAT"],
          financialHealth: "Strong",
          capacityUtilization: 85,
          priceCompetitiveness: 4.3,
          innovationScore: 4.0,
          sustainabilityScore: 4.4,
        },
        {
          id: "3",
          name: "Tech Solutions Corp",
          spend: 750000,
          spendPercentage: 9.1,
          onTimeDelivery: 92.3,
          qualityAcceptance: 94.7,
          invoiceAccuracy: 88.4,
          overallScore: 4.1,
          riskRating: "Medium",
          category: "Technology",
          location: "Asia Pacific",
          contractStatus: "Expiring",
          trend: -1.5,
          relationshipLength: "3 years",
          lastOrderDate: "2024-01-08",
          paymentTerms: "Net 45",
          avgOrderValue: 125000,
          orderFrequency: "Monthly",
          certifications: ["ISO 27001"],
          financialHealth: "Good",
          capacityUtilization: 65,
          priceCompetitiveness: 4.0,
          innovationScore: 4.8,
          sustainabilityScore: 3.8,
        },
        {
          id: "4",
          name: "Manufacturing Partners",
          spend: 2100000,
          spendPercentage: 25.5,
          onTimeDelivery: 89.7,
          qualityAcceptance: 91.2,
          invoiceAccuracy: 93.6,
          overallScore: 3.8,
          riskRating: "Medium",
          category: "Manufacturing",
          location: "Europe",
          contractStatus: "Active",
          trend: 0.8,
          relationshipLength: "12 years",
          lastOrderDate: "2024-01-09",
          paymentTerms: "Net 30",
          avgOrderValue: 180000,
          orderFrequency: "Bi-weekly",
          certifications: ["ISO 9001", "TS 16949"],
          financialHealth: "Good",
          capacityUtilization: 92,
          priceCompetitiveness: 3.8,
          innovationScore: 3.5,
          sustainabilityScore: 4.2,
        },
        {
          id: "5",
          name: "Energy Systems LLC",
          spend: 650000,
          spendPercentage: 7.9,
          onTimeDelivery: 85.4,
          qualityAcceptance: 87.9,
          invoiceAccuracy: 82.1,
          overallScore: 3.2,
          riskRating: "High",
          category: "Energy",
          location: "North America",
          contractStatus: "Expiring",
          trend: -8.3,
          relationshipLength: "4 years",
          lastOrderDate: "2023-12-20",
          paymentTerms: "Net 60",
          avgOrderValue: 95000,
          orderFrequency: "Quarterly",
          certifications: ["ISO 9001"],
          financialHealth: "Fair",
          capacityUtilization: 55,
          priceCompetitiveness: 3.2,
          innovationScore: 2.8,
          sustainabilityScore: 3.5,
        },
        {
          id: "6",
          name: "Professional Services Group",
          spend: 420000,
          spendPercentage: 5.1,
          onTimeDelivery: 97.1,
          qualityAcceptance: 98.8,
          invoiceAccuracy: 95.3,
          overallScore: 4.5,
          riskRating: "Low",
          category: "Services",
          location: "Global",
          contractStatus: "Renewed",
          trend: 3.7,
          relationshipLength: "6 years",
          lastOrderDate: "2024-01-11",
          paymentTerms: "Net 30",
          avgOrderValue: 35000,
          orderFrequency: "Weekly",
          certifications: ["ISO 9001", "SOC 2"],
          financialHealth: "Strong",
          capacityUtilization: 72,
          priceCompetitiveness: 4.4,
          innovationScore: 4.6,
          sustainabilityScore: 4.7,
        },
      ],
      performanceMetrics: {
        onTimeDeliveryTrend: [94.2, 93.8, 94.5, 94.0, 94.2, 94.8, 94.2],
        qualityAcceptanceTrend: [96.8, 96.5, 97.1, 96.8, 97.0, 96.9, 96.8],
        invoiceAccuracyTrend: [93.2, 92.8, 93.5, 93.0, 93.2, 93.6, 93.2],
        costSavings: 125000,
        costAvoidance: 85000,
        supplierDiversity: 35.2,
        contractCompliance: 92.8,
      },
      riskAnalysis: {
        highRiskSuppliers: 1,
        mediumRiskSuppliers: 2,
        lowRiskSuppliers: 3,
        expiringContracts: 2,
        singleSourceSuppliers: 1,
        geographicConcentration: 45.2,
        categoryConcentration: 25.5,
      },
      recommendations: [
        {
          type: "Performance Improvement",
          supplier: "Energy Systems LLC",
          action: "Develop improvement plan for delivery and quality metrics",
          priority: "High",
          timeline: "30 days",
        },
        {
          type: "Contract Renewal",
          supplier: "Tech Solutions Corp",
          action: "Negotiate contract renewal with performance clauses",
          priority: "Medium",
          timeline: "60 days",
        },
        {
          type: "Risk Mitigation",
          supplier: "Manufacturing Partners",
          action: "Develop backup supplier for high-volume category",
          priority: "Medium",
          timeline: "90 days",
        },
      ],
    }

    return NextResponse.json(supplierPerformanceData)
  } catch (error) {
    console.error("Supplier Performance API Error:", error)
    return NextResponse.json(
      { error: "Failed to fetch supplier performance data" },
      { status: 500 }
    )
  }
}
