import { NextRequest, NextResponse } from "next/server"

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const period = searchParams.get("period") || "ytd"
    const comparisonPeriod =
      searchParams.get("comparisonPeriod") || "prior-year"
    const businessUnits = searchParams.get("businessUnits")?.split(",") || []
    const productLines = searchParams.get("productLines")?.split(",") || []
    const geography = searchParams.get("geography")?.split(",") || []

    // Mock data - in real implementation, this would come from database
    const customerProfitabilityData = {
      summary: {
        totalRevenue: 8500000,
        totalOutstandingAR: 2300000,
        totalCustomers: 8,
        averageProfitMargin: 18.2,
      },
      customers: [
        {
          id: "1",
          name: "Acme Corporation",
          revenue: 2500000,
          profitMargin: 22.5,
          outstandingAR: 450000,
          tier: "Platinum",
          quadrant: "Stars",
          trend: 15.2,
          riskRating: "Low",
          category: "Manufacturing",
          location: "North America",
          relationshipLength: "5 years",
          lastOrderDate: "2024-01-10",
          paymentTerms: "Net 30",
          avgOrderValue: 125000,
          orderFrequency: "Monthly",
          costToServe: 45000,
          lifetimeValue: 12500000,
        },
        {
          id: "2",
          name: "TechStart Inc",
          revenue: 1800000,
          profitMargin: 28.3,
          outstandingAR: 320000,
          tier: "Platinum",
          quadrant: "Stars",
          trend: 22.1,
          riskRating: "Low",
          category: "Technology",
          location: "North America",
          relationshipLength: "3 years",
          lastOrderDate: "2024-01-12",
          paymentTerms: "Net 15",
          avgOrderValue: 90000,
          orderFrequency: "Bi-weekly",
          costToServe: 28000,
          lifetimeValue: 8500000,
        },
        {
          id: "3",
          name: "Global Manufacturing",
          revenue: 3200000,
          profitMargin: 12.8,
          outstandingAR: 680000,
          tier: "Gold",
          quadrant: "Cash Cows",
          trend: 8.5,
          riskRating: "Medium",
          category: "Manufacturing",
          location: "Global",
          relationshipLength: "8 years",
          lastOrderDate: "2024-01-08",
          paymentTerms: "Net 45",
          avgOrderValue: 200000,
          orderFrequency: "Monthly",
          costToServe: 85000,
          lifetimeValue: 18500000,
        },
        {
          id: "4",
          name: "Innovation Labs",
          revenue: 450000,
          profitMargin: 35.2,
          outstandingAR: 85000,
          tier: "Silver",
          quadrant: "Question Marks",
          trend: 45.6,
          riskRating: "Low",
          category: "Research & Development",
          location: "Europe",
          relationshipLength: "2 years",
          lastOrderDate: "2024-01-14",
          paymentTerms: "Net 30",
          avgOrderValue: 75000,
          orderFrequency: "Quarterly",
          costToServe: 15000,
          lifetimeValue: 2100000,
        },
        {
          id: "5",
          name: "Legacy Systems Co",
          revenue: 1200000,
          profitMargin: 8.9,
          outstandingAR: 280000,
          tier: "Bronze",
          quadrant: "Dogs",
          trend: -5.2,
          riskRating: "High",
          category: "Technology",
          location: "North America",
          relationshipLength: "12 years",
          lastOrderDate: "2023-12-15",
          paymentTerms: "Net 60",
          avgOrderValue: 60000,
          orderFrequency: "Irregular",
          costToServe: 35000,
          lifetimeValue: 4500000,
        },
        {
          id: "6",
          name: "Future Enterprises",
          revenue: 750000,
          profitMargin: 31.7,
          outstandingAR: 120000,
          tier: "Silver",
          quadrant: "Question Marks",
          trend: 18.9,
          riskRating: "Low",
          category: "Services",
          location: "Asia Pacific",
          relationshipLength: "1 year",
          lastOrderDate: "2024-01-11",
          paymentTerms: "Net 30",
          avgOrderValue: 50000,
          orderFrequency: "Monthly",
          costToServe: 18000,
          lifetimeValue: 3200000,
        },
        {
          id: "7",
          name: "MegaCorp International",
          revenue: 4200000,
          profitMargin: 15.4,
          outstandingAR: 750000,
          tier: "Gold",
          quadrant: "Cash Cows",
          trend: 3.2,
          riskRating: "Medium",
          category: "Manufacturing",
          location: "Global",
          relationshipLength: "10 years",
          lastOrderDate: "2024-01-09",
          paymentTerms: "Net 45",
          avgOrderValue: 180000,
          orderFrequency: "Monthly",
          costToServe: 95000,
          lifetimeValue: 22000000,
        },
        {
          id: "8",
          name: "Startup Ventures",
          revenue: 280000,
          profitMargin: 42.1,
          outstandingAR: 45000,
          tier: "Silver",
          quadrant: "Question Marks",
          trend: 67.3,
          riskRating: "Medium",
          category: "Technology",
          location: "North America",
          relationshipLength: "6 months",
          lastOrderDate: "2024-01-13",
          paymentTerms: "Net 15",
          avgOrderValue: 35000,
          orderFrequency: "Bi-weekly",
          costToServe: 8000,
          lifetimeValue: 1200000,
        },
      ],
      quadrantAnalysis: {
        Stars: {
          count: 2,
          revenue: 4300000,
          avgMargin: 25.4,
          recommendation: "Nurture & Expand",
          actionItems: [
            "Increase account management attention",
            "Explore upselling opportunities",
            "Consider strategic partnership",
          ],
        },
        "Question Marks": {
          count: 3,
          revenue: 1480000,
          avgMargin: 36.3,
          recommendation: "Growth Potential",
          actionItems: [
            "Develop growth strategy",
            "Increase marketing investment",
            "Monitor closely for expansion",
          ],
        },
        "Cash Cows": {
          count: 2,
          revenue: 7400000,
          avgMargin: 14.1,
          recommendation: "Efficiency Focus",
          actionItems: [
            "Optimize cost structure",
            "Improve operational efficiency",
            "Maintain market share",
          ],
        },
        Dogs: {
          count: 1,
          revenue: 1200000,
          avgMargin: 8.9,
          recommendation: "Restructure or Exit",
          actionItems: [
            "Review relationship viability",
            "Consider restructuring terms",
            "Evaluate exit strategy",
          ],
        },
      },
      trends: {
        revenueGrowth: 12.5,
        marginImprovement: 3.2,
        customerRetention: 94.2,
        newCustomerAcquisition: 8,
        churnRate: 2.1,
      },
    }

    return NextResponse.json(customerProfitabilityData)
  } catch (error) {
    console.error("Customer Profitability API Error:", error)
    return NextResponse.json(
      { error: "Failed to fetch customer profitability data" },
      { status: 500 }
    )
  }
}
