import { format } from "date-fns"

import { clientDateFormat } from "@/lib/date-utils"

const buildDefaultCbPettyCashDetails = (dateFormat: string) => ({
  paymentId: "0",
  paymentNo: "",
  itemNo: 0,
  seqNo: 0,
  glId: 0,
  glCode: "",
  glName: "",
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  remarks: "",
  gstId: 0,
  gstName: "",
  gstPercentage: 0,
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  departmentId: 0,
  departmentCode: "",
  departmentName: "",
  employeeId: 0,
  employeeCode: "",
  employeeName: "",
  portId: 0,
  portCode: "",
  portName: "",
  vesselId: 0,
  vesselCode: "",
  vesselName: "",
  bargeId: 0,
  bargeCode: "",
  bargeName: "",
  voyageId: 0,
  voyageNo: "",
  editVersion: 0,
})

const buildDefaultCbPettyCash = (dateFormat: string) => ({
  companyId: 0,
  paymentId: "0",
  paymentNo: "",
  referenceNo: "",
  suppCbPettyCashNo: "",
  trnDate: format(new Date(), dateFormat),
  accountDate: format(new Date(), dateFormat),
  currencyId: 0,
  exhRate: 0,
  ctyExhRate: 0,
  bankId: 0,
  paymentTypeId: 0,
  chequeNo: "",
  chequeDate: "",
  bankChgGLId: 0,
  bankChgAmt: 0,
  bankChgLocalAmt: 0,
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  gstClaimDate: format(new Date(), dateFormat),
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  totAmtAftGst: 0,
  totLocalAmtAftGst: 0,
  totCtyAmtAftGst: 0,
  remarks: "",
  payeeTo: "",
  moduleFrom: "",
  createById: 0,
  createDate: format(new Date(), dateFormat),
  editById: "",
  editDate: "",
  isCancel: false,
  cancelById: 0,
  cancelDate: "",
  cancelRemarks: "",
  createBy: "",
  editBy: "",
  cancelBy: "",
  editVersion: 0,
  isPost: false,
  postById: "",
  postDate: "",
  appStatusId: "",
  appById: "",
  appDate: "",
  data_details: [],
})

// Function to get default values with custom date format
export const getDefaultValues = (dateFormat: string = clientDateFormat) => ({
  defaultCbPettyCash: buildDefaultCbPettyCash(dateFormat),
  defaultCbPettyCashDetails: buildDefaultCbPettyCashDetails(dateFormat),
})

export const defaultCbPettyCash = buildDefaultCbPettyCash(clientDateFormat)
export const defaultCbPettyCashDetails =
  buildDefaultCbPettyCashDetails(clientDateFormat)
