import { NextRequest, NextResponse } from "next/server"

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const period = searchParams.get("period") || "ytd"
    const priority = searchParams.get("priority") || "all"
    const category = searchParams.get("category") || "all"
    const status = searchParams.get("status") || "all"
    const businessUnits = searchParams.get("businessUnits")?.split(",") || []

    // Mock data - in real implementation, this would come from database
    const exceptionAlertsData = {
      summary: {
        total: 8,
        critical: 2,
        warning: 3,
        informational: 3,
        open: 4,
        investigating: 3,
        resolved: 1,
        dismissed: 0,
        avgResolutionTime: 2.5,
        falsePositiveRate: 12.5,
      },
      alerts: [
        {
          id: "1",
          type: "Duplicate Payment Risk",
          category: "Control Failures",
          priority: "Critical",
          title: "Potential Duplicate Invoice Payment",
          description:
            "Invoice #INV-2024-001 for $125,000 from Premium Materials Ltd appears to match a previous payment within 7 days.",
          detectedDate: "2024-01-15T10:30:00Z",
          assignedTo: "Finance Team",
          status: "Investigating",
          impact: "High - Potential $125,000 duplicate payment",
          confidence: 95,
          relatedTransactions: ["PAY-2024-045", "INV-2024-001"],
          relatedDocuments: [
            "invoice_inv_2024_001.pdf",
            "payment_pay_2024_045.pdf",
          ],
          investigationNotes:
            "Verified - legitimate duplicate payment prevented",
          resolutionDate: null,
          resolutionNotes: null,
          tags: ["duplicate", "payment", "control"],
          businessUnit: "Finance",
          escalationLevel: 2,
          slaStatus: "Within SLA",
          estimatedImpact: 125000,
        },
        {
          id: "2",
          type: "Unusual Journal Entry",
          category: "Transaction Anomalies",
          priority: "Warning",
          title: "Large Journal Entry Detected",
          description:
            "Journal entry JE-2024-156 for $2,500,000 posted outside normal business hours (2:30 AM) with Z-score of 4.2.",
          detectedDate: "2024-01-14T02:30:00Z",
          assignedTo: "Accounting Team",
          status: "Open",
          impact: "Medium - Requires verification of authorization",
          confidence: 78,
          relatedTransactions: ["JE-2024-156"],
          relatedDocuments: ["journal_entry_je_2024_156.pdf"],
          investigationNotes: "Pending review by accounting manager",
          resolutionDate: null,
          resolutionNotes: null,
          tags: ["journal", "anomaly", "authorization"],
          businessUnit: "Accounting",
          escalationLevel: 1,
          slaStatus: "Within SLA",
          estimatedImpact: 2500000,
        },
        {
          id: "3",
          type: "New High-Risk Vendor",
          category: "Vendor/Customer Risks",
          priority: "Warning",
          title: "New Vendor with High Risk Score",
          description:
            "New vendor 'Quick Solutions Inc' added with risk score of 8.2/10. No prior business history found.",
          detectedDate: "2024-01-13T14:20:00Z",
          assignedTo: "Procurement Team",
          status: "Investigating",
          impact: "Medium - Requires additional due diligence",
          confidence: 82,
          relatedTransactions: ["PO-2024-089"],
          relatedDocuments: ["vendor_application_quick_solutions.pdf"],
          investigationNotes:
            "Conducting background check and financial review",
          resolutionDate: null,
          resolutionNotes: null,
          tags: ["vendor", "risk", "due-diligence"],
          businessUnit: "Procurement",
          escalationLevel: 1,
          slaStatus: "Within SLA",
          estimatedImpact: 85000,
        },
        {
          id: "4",
          type: "Payment Pattern Change",
          category: "Vendor/Customer Risks",
          priority: "Informational",
          title: "Customer Payment Pattern Deviation",
          description:
            "Acme Corporation payment pattern changed from 30-day average to 45-day average over last 3 invoices.",
          detectedDate: "2024-01-12T09:15:00Z",
          assignedTo: "AR Team",
          status: "Open",
          impact: "Low - Monitor for trend continuation",
          confidence: 65,
          relatedTransactions: ["INV-2024-023", "INV-2024-024", "INV-2024-025"],
          relatedDocuments: [],
          investigationNotes: "Monitoring customer relationship",
          resolutionDate: null,
          resolutionNotes: null,
          tags: ["customer", "payment", "pattern"],
          businessUnit: "Sales",
          escalationLevel: 0,
          slaStatus: "Within SLA",
          estimatedImpact: 450000,
        },
        {
          id: "5",
          type: "PO Without Competitive Bid",
          category: "Process Exceptions",
          priority: "Warning",
          title: "High-Value PO Without Competitive Bidding",
          description:
            "Purchase Order PO-2024-092 for $850,000 awarded without competitive bidding process. Exceeds threshold of $500,000.",
          detectedDate: "2024-01-11T16:45:00Z",
          assignedTo: "Procurement Team",
          status: "Investigating",
          impact: "Medium - Compliance review required",
          confidence: 88,
          relatedTransactions: ["PO-2024-092"],
          relatedDocuments: ["po_2024_092.pdf", "justification_memo.pdf"],
          investigationNotes: "Reviewing justification and approval process",
          resolutionDate: null,
          resolutionNotes: null,
          tags: ["procurement", "compliance", "bidding"],
          businessUnit: "Procurement",
          escalationLevel: 1,
          slaStatus: "Within SLA",
          estimatedImpact: 850000,
        },
        {
          id: "6",
          type: "Contract Expiration Alert",
          category: "Process Exceptions",
          priority: "Informational",
          title: "Critical Contract Expiring Soon",
          description:
            "Master Service Agreement with Global Logistics Inc expires in 45 days. Auto-renewal clause requires 60-day notice.",
          detectedDate: "2024-01-10T11:30:00Z",
          assignedTo: "Legal Team",
          status: "Open",
          impact: "High - Service disruption risk",
          confidence: 100,
          relatedTransactions: [],
          relatedDocuments: ["msa_global_logistics_2022.pdf"],
          investigationNotes: "Initiating renewal negotiations",
          resolutionDate: null,
          resolutionNotes: null,
          tags: ["contract", "expiration", "renewal"],
          businessUnit: "Legal",
          escalationLevel: 0,
          slaStatus: "Within SLA",
          estimatedImpact: 980000,
        },
        {
          id: "7",
          type: "Segregation of Duties Violation",
          category: "Control Failures",
          priority: "Critical",
          title: "SoD Violation in Invoice Processing",
          description:
            "Same user (john.doe@company.com) created and approved invoice INV-2024-031. Violates segregation of duties policy.",
          detectedDate: "2024-01-09T13:20:00Z",
          assignedTo: "Internal Audit",
          status: "Resolved",
          impact: "High - Control weakness identified",
          confidence: 100,
          relatedTransactions: ["INV-2024-031"],
          relatedDocuments: ["sod_violation_report.pdf"],
          investigationNotes:
            "User training completed, system controls updated",
          resolutionDate: "2024-01-12T14:30:00Z",
          resolutionNotes:
            "Control weakness addressed through system configuration and user training",
          tags: ["sod", "violation", "control"],
          businessUnit: "Internal Audit",
          escalationLevel: 3,
          slaStatus: "Resolved",
          estimatedImpact: 75000,
        },
        {
          id: "8",
          type: "Unusual Invoice Amount",
          category: "Transaction Anomalies",
          priority: "Warning",
          title: "Invoice Amount Outside Normal Range",
          description:
            "Invoice INV-2024-032 for $15,000 is 300% higher than vendor's typical invoice amounts ($5,000 average).",
          detectedDate: "2024-01-08T08:15:00Z",
          assignedTo: "AP Team",
          status: "Dismissed",
          impact: "Low - Verified as legitimate service expansion",
          confidence: 72,
          relatedTransactions: ["INV-2024-032"],
          relatedDocuments: [
            "invoice_inv_2024_032.pdf",
            "service_agreement_amendment.pdf",
          ],
          investigationNotes: "Verified as legitimate service expansion",
          resolutionDate: "2024-01-10T10:45:00Z",
          resolutionNotes:
            "Invoice amount justified by expanded service agreement",
          tags: ["invoice", "amount", "anomaly"],
          businessUnit: "AP",
          escalationLevel: 0,
          slaStatus: "Resolved",
          estimatedImpact: 15000,
        },
      ],
      categories: [
        {
          name: "Control Failures",
          count: 2,
          critical: 2,
          warning: 0,
          informational: 0,
          description: "Internal control violations and weaknesses",
          avgResolutionTime: 1.5,
        },
        {
          name: "Transaction Anomalies",
          count: 2,
          critical: 0,
          warning: 1,
          informational: 1,
          description: "Unusual transaction patterns and amounts",
          avgResolutionTime: 2.0,
        },
        {
          name: "Vendor/Customer Risks",
          count: 2,
          critical: 0,
          warning: 1,
          informational: 1,
          description: "Risk indicators related to vendors and customers",
          avgResolutionTime: 3.0,
        },
        {
          name: "Process Exceptions",
          count: 2,
          critical: 0,
          warning: 1,
          informational: 1,
          description: "Process compliance and policy violations",
          avgResolutionTime: 4.0,
        },
      ],
      trends: {
        dailyAlerts: [2, 1, 3, 1, 2, 0, 1], // Last 7 days
        resolutionTime: [2.5, 2.8, 2.2, 2.6, 2.4, 2.7, 2.3], // Last 7 days
        falsePositiveRate: [15, 12, 18, 10, 14, 11, 13], // Last 7 days
        categoryDistribution: {
          "Control Failures": 25,
          "Transaction Anomalies": 25,
          "Vendor/Customer Risks": 25,
          "Process Exceptions": 25,
        },
      },
      performanceMetrics: {
        detectionAccuracy: 87.5,
        falsePositiveRate: 12.5,
        avgResolutionTime: 2.5,
        slaCompliance: 95.0,
        escalationRate: 15.0,
        automationRate: 65.0,
      },
      recommendations: [
        {
          type: "Process Improvement",
          priority: "High",
          action: "Implement automated duplicate payment detection",
          impact: "Reduce duplicate payment risks by 80%",
          timeline: "30 days",
          owner: "IT Team",
        },
        {
          type: "Training",
          priority: "Medium",
          action: "Conduct SoD training for all users",
          impact: "Reduce SoD violations by 60%",
          timeline: "60 days",
          owner: "HR Team",
        },
        {
          type: "System Enhancement",
          priority: "Low",
          action: "Improve anomaly detection algorithms",
          impact: "Reduce false positives by 25%",
          timeline: "90 days",
          owner: "Data Science Team",
        },
      ],
    }

    return NextResponse.json(exceptionAlertsData)
  } catch (error) {
    console.error("Exception Alerts API Error:", error)
    return NextResponse.json(
      { error: "Failed to fetch exception alerts data" },
      { status: 500 }
    )
  }
}
