export interface IGlTransactionDetails {
  DocumentNo: string
  ReferenceNo: string
  AccountDate: string
  CurrencyId: number
  CurrencyCode: string
  CurrencyName: string
  ExhRate: number
  CtyExhRate: number
  BankId: string
  BankCode: string
  BankName: string
  GLId: string
  GLCode: string
  GLName: string
  IsDebit: boolean
  TotAmt: number
  TotLocalAmt: number
  TotCtyAmt: number
  gstId: number
  gstCode: string
  gstName: string
  gstAmt: number
  gstLocalAmt: number
  gstCtyAmt: number
  remarks: string
  departmentId: number
  departmentCode: string
  departmentName: string
  employeeId: number
  employeeCode: string
  employeeName: string
  portId: number
  portCode: string
  portName: string
  vesselId: number
  vesselCode: string
  vesselName: string
  voyageId: number
  voyageNo: string
  bargeId: number
  bargeCode: string
  bargeName: string
  productId: number
  productCode: string
  productName: string
  supplierId: number
  supplierCode: string
  supplierName: string
  moduleFrom: string
  createById: number
  createByCode: string
  createByName: string
  createDate: string
}

export interface IPaymentDetails {
  ModuleId: number
  TransactionId: number
  TrnType: string
  DocumentId: number
  DocumentNO: string
  ReferenceNo: string
  AccountDate: number
  TotAmt: number
  TotLocalAmt: number
  AllAmt: number
  AllLocalAmt: number
  ExGainLoss: string
}

export interface ICustomerInvoiceDetails {
  invoiceId: string
  invoiceNo: string
  referenceNo: string
  accountDate: string
  currencyId: number
  currencyCode: string
  currencyName: string
  exhRate: number
  totAmt: number
  totLocalAmt: number
  totCtyAmt: number
  gstAmt: number
  gstLocalAmt: number
  gstCtyAmt: number
  totAmtAftGst: number
  totLocalAmtAftGst: number
  moduleFrom: string
  createByCode: string
  createByName: string
  createDate: string
  editByCode: string
  editByName: string
  editDate: string
}

export interface ISupplierInvoiceDetails {
  invoiceId: string
  invoiceNo: string
  referenceNo: string
  accountDate: string
  currencyId: number
  currencyCode: string
  currencyName: string
  exhRate: number
  totAmt: number
  totLocalAmt: number
  totCtyAmt: number
  gstAmt: number
  gstLocalAmt: number
  gstCtyAmt: number
  totAmtAftGst: number
  totLocalAmtAftGst: number
  moduleFrom: string
  createByCode: string
  createByName: string
  createDate: string
  editByCode: string
  editByName: string
  editDate: string
}
