import { format } from "date-fns"

import { clientDateFormat } from "@/lib/date-utils"

const defaultPaymentDetails = {
  paymentId: "0",
  paymentNo: "",
  itemNo: 0,
  seqNo: 0,
  glId: 0,
  glCode: "",
  glName: "",
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  remarks: "",
  gstId: 0,
  gstName: "",
  gstPercentage: 0,
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  departmentId: 0,
  departmentCode: "",
  departmentName: "",
  employeeId: 0,
  employeeCode: "",
  employeeName: "",
  portId: 0,
  portCode: "",
  portName: "",
  vesselId: 0,
  vesselCode: "",
  vesselName: "",
  bargeId: 0,
  bargeCode: "",
  bargeName: "",
  voyageId: 0,
  voyageNo: "",
  editVersion: 0,
}

const defaultPayment = {
  companyId: 0,
  paymentId: "0",
  paymentNo: "",
  referenceNo: "",
  trnDate: format(new Date(), clientDateFormat),
  accountDate: format(new Date(), clientDateFormat),
  currencyId: 0,
  exhRate: 0,
  ctyExhRate: 0,
  paymentTypeId: 0,
  bankId: 0,
  chequeNo: "",
  chequeDate: "",
  bankChgGLId: 0,
  bankChgAmt: 0,
  bankChgLocalAmt: 0,
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  gstClaimDate: format(new Date(), clientDateFormat),
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  totAmtAftGst: 0,
  totLocalAmtAftGst: 0,
  totCtyAmtAftGst: 0,
  remarks: "",
  payeeTo: "",
  moduleFrom: "",
  createDate: format(new Date(), clientDateFormat),
  editDate: null,
  isCancel: false,
  cancelDate: null,
  cancelRemarks: null,
  createBy: "",
  editBy: "",
  cancelBy: "",
  editVersion: 0,
  isPost: false,
  postDate: null,
  appStatusId: null,
  appById: null,
  appDate: null,
  data_details: [],
}

// Function to get default values with custom date format
export const getDefaultValues = (dateFormat: string = clientDateFormat) => {
  return {
    defaultPayment: {
      ...defaultPayment,
      trnDate: format(new Date(), dateFormat),
      accountDate: format(new Date(), dateFormat),
      chequeDate: "",
      gstClaimDate: format(new Date(), dateFormat),
      createDate: format(new Date(), dateFormat),
    },
    defaultPaymentDetails: {
      ...defaultPaymentDetails,
    },
  }
}

export { defaultPayment, defaultPaymentDetails }
