// import { IEmployee } from "@/interfaces/employee"
// import { IPayrollComponent, IPayrollEmployee } from "@/interfaces/payroll"

// // Dummy Employee Data
// export const dummyEmployees: IEmployee[] = [
//   {
//     employeeId: 1,
//     companyId: 1,
//     code: "EMP001",
//     employeeName: "George K. Thomas",
//     departmentId: 1,
//     departmentName: "IT Department",
//     designationId: 1,
//     designationName: "Manager",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Married",
//     dob: "1985-03-15",
//     joinDate: "2020-01-15",
//     phoneNo: "+971-50-123-4567",
//     offEmailAdd: "george.thomas@company.com",
//     bankName: "Emirates NBD",
//     accountNo: "AE123456789012345678901",
//     nationality: "Indian",
//     emiratesIDNo: "784-1985-1234567-8",
//     emiratesIDExpiry: "2025-12-31",
//     isActive: true,
//     createDate: "2020-01-15",
//     createBy: "admin",
//   },
//   {
//     employeeId: 2,
//     companyId: 1,
//     code: "EMP002",
//     employeeName: "Jayasankar C.",
//     departmentId: 2,
//     departmentName: "Finance",
//     designationId: 2,
//     designationName: "Senior Executive",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Single",
//     dob: "1990-07-22",
//     joinDate: "2021-03-10",
//     phoneNo: "+971-50-234-5678",
//     offEmailAdd: "jayasankar.c@company.com",
//     bankName: "Abu Dhabi Commercial Bank",
//     accountNo: "AE234567890123456789012",
//     nationality: "Indian",
//     emiratesIDNo: "784-1990-2345678-9",
//     emiratesIDExpiry: "2026-06-30",
//     isActive: true,
//     createDate: "2021-03-10",
//     createBy: "admin",
//   },
//   {
//     employeeId: 3,
//     companyId: 1,
//     code: "EMP003",
//     employeeName: "Sonia Seloveres",
//     departmentId: 3,
//     departmentName: "HR",
//     designationId: 2,
//     designationName: "Senior Executive",
//     genderId: 2,
//     genderName: "Female",
//     martialStatus: "Married",
//     dob: "1988-11-08",
//     joinDate: "2020-06-20",
//     phoneNo: "+971-50-345-6789",
//     offEmailAdd: "sonia.seloveres@company.com",
//     bankName: "Dubai Islamic Bank",
//     accountNo: "AE345678901234567890123",
//     nationality: "Filipino",
//     emiratesIDNo: "784-1988-3456789-0",
//     emiratesIDExpiry: "2025-09-15",
//     isActive: true,
//     createDate: "2020-06-20",
//     createBy: "admin",
//   },
//   {
//     employeeId: 4,
//     companyId: 1,
//     code: "EMP004",
//     employeeName: "Shamaj E. Vasu",
//     departmentId: 1,
//     departmentName: "IT Department",
//     designationId: 3,
//     designationName: "Developer",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Single",
//     dob: "1992-04-12",
//     joinDate: "2022-01-05",
//     phoneNo: "+971-50-456-7890",
//     offEmailAdd: "shamaj.vasu@company.com",
//     bankName: "Mashreq Bank",
//     accountNo: "AE456789012345678901234",
//     nationality: "Indian",
//     emiratesIDNo: "784-1992-4567890-1",
//     emiratesIDExpiry: "2027-03-20",
//     isActive: true,
//     createDate: "2022-01-05",
//     createBy: "admin",
//   },
//   {
//     employeeId: 5,
//     companyId: 1,
//     code: "EMP005",
//     employeeName: "Priyesh T.V.",
//     departmentId: 4,
//     departmentName: "Operations",
//     designationId: 2,
//     designationName: "Senior Executive",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Married",
//     dob: "1987-09-30",
//     joinDate: "2021-08-15",
//     phoneNo: "+971-50-567-8901",
//     offEmailAdd: "priyesh.tv@company.com",
//     bankName: "Commercial Bank of Dubai",
//     accountNo: "AE567890123456789012345",
//     nationality: "Indian",
//     emiratesIDNo: "784-1987-5678901-2",
//     emiratesIDExpiry: "2026-11-10",
//     isActive: true,
//     createDate: "2021-08-15",
//     createBy: "admin",
//   },
//   {
//     employeeId: 6,
//     companyId: 1,
//     code: "EMP006",
//     employeeName: "Babu Unni M",
//     departmentId: 5,
//     departmentName: "Logistics",
//     designationId: 4,
//     designationName: "Coordinator",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Married",
//     dob: "1983-12-05",
//     joinDate: "2020-11-12",
//     phoneNo: "+971-50-678-9012",
//     offEmailAdd: "babu.unni@company.com",
//     bankName: "Union National Bank",
//     accountNo: "AE678901234567890123456",
//     nationality: "Indian",
//     emiratesIDNo: "784-1983-6789012-3",
//     emiratesIDExpiry: "2025-08-25",
//     isActive: true,
//     createDate: "2020-11-12",
//     createBy: "admin",
//   },
//   {
//     employeeId: 7,
//     companyId: 1,
//     code: "EMP007",
//     employeeName: "Gijo Thomas",
//     departmentId: 2,
//     departmentName: "Finance",
//     designationId: 3,
//     designationName: "Accountant",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Single",
//     dob: "1991-06-18",
//     joinDate: "2022-03-22",
//     phoneNo: "+971-50-789-0123",
//     offEmailAdd: "gijo.thomas@company.com",
//     bankName: "First Abu Dhabi Bank",
//     accountNo: "AE789012345678901234567",
//     nationality: "Indian",
//     emiratesIDNo: "784-1991-7890123-4",
//     emiratesIDExpiry: "2027-01-15",
//     isActive: true,
//     createDate: "2022-03-22",
//     createBy: "admin",
//   },
//   {
//     employeeId: 8,
//     companyId: 1,
//     code: "EMP008",
//     employeeName: "Mohammed Akbar",
//     departmentId: 6,
//     departmentName: "Sales",
//     designationId: 2,
//     designationName: "Senior Executive",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Married",
//     dob: "1986-02-14",
//     joinDate: "2021-05-08",
//     phoneNo: "+971-50-890-1234",
//     offEmailAdd: "mohammed.akbar@company.com",
//     bankName: "Emirates Islamic Bank",
//     accountNo: "AE890123456789012345678",
//     nationality: "Pakistani",
//     emiratesIDNo: "784-1986-8901234-5",
//     emiratesIDExpiry: "2026-04-30",
//     isActive: true,
//     createDate: "2021-05-08",
//     createBy: "admin",
//   },
//   {
//     employeeId: 9,
//     companyId: 1,
//     code: "EMP009",
//     employeeName: "Shibu Thulaseedharan",
//     departmentId: 1,
//     departmentName: "IT Department",
//     designationId: 3,
//     designationName: "Developer",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Single",
//     dob: "1993-08-25",
//     joinDate: "2022-07-10",
//     phoneNo: "+971-50-901-2345",
//     offEmailAdd: "shibu.thulaseedharan@company.com",
//     bankName: "Sharjah Islamic Bank",
//     accountNo: "AE901234567890123456789",
//     nationality: "Indian",
//     emiratesIDNo: "784-1993-9012345-6",
//     emiratesIDExpiry: "2027-07-20",
//     isActive: true,
//     createDate: "2022-07-10",
//     createBy: "admin",
//   },
//   {
//     employeeId: 10,
//     companyId: 1,
//     code: "EMP0010",
//     employeeName: "Vyas M.V.",
//     departmentId: 3,
//     departmentName: "HR",
//     designationId: 4,
//     designationName: "Coordinator",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Married",
//     dob: "1989-01-20",
//     joinDate: "2021-10-15",
//     phoneNo: "+971-50-012-3456",
//     offEmailAdd: "vyas.mv@company.com",
//     bankName: "Rakbank",
//     accountNo: "AE012345678901234567890",
//     nationality: "Indian",
//     emiratesIDNo: "784-1989-0123456-7",
//     emiratesIDExpiry: "2026-12-05",
//     isActive: true,
//     createDate: "2021-10-15",
//     createBy: "admin",
//   },
//   {
//     employeeId: 11,
//     companyId: 1,
//     code: "EMP0011",
//     employeeName: "Asghar Ali Shaik",
//     departmentId: 4,
//     departmentName: "Operations",
//     designationId: 3,
//     designationName: "Coordinator",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Single",
//     dob: "1990-10-12",
//     joinDate: "2022-02-28",
//     phoneNo: "+971-50-123-4567",
//     offEmailAdd: "asghar.shaik@company.com",
//     bankName: "Ajman Bank",
//     accountNo: "AE123456789012345678901",
//     nationality: "Pakistani",
//     emiratesIDNo: "784-1990-1234567-8",
//     emiratesIDExpiry: "2027-05-15",
//     isActive: true,
//     createDate: "2022-02-28",
//     createBy: "admin",
//   },
//   {
//     employeeId: 12,
//     companyId: 1,
//     code: "EMP0012",
//     employeeName: "Vishnu Sreekumar",
//     departmentId: 5,
//     departmentName: "Logistics",
//     designationId: 4,
//     designationName: "Coordinator",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Married",
//     dob: "1984-05-08",
//     joinDate: "2020-09-20",
//     phoneNo: "+971-50-234-5678",
//     offEmailAdd: "vishnu.sreekumar@company.com",
//     bankName: "Al Hilal Bank",
//     accountNo: "AE234567890123456789012",
//     nationality: "Indian",
//     emiratesIDNo: "784-1984-2345678-9",
//     emiratesIDExpiry: "2025-10-30",
//     isActive: true,
//     createDate: "2020-09-20",
//     createBy: "admin",
//   },
//   {
//     employeeId: 13,
//     companyId: 1,
//     code: "EMP0013",
//     employeeName: "Badrudin Mama Glandel",
//     departmentId: 6,
//     departmentName: "Sales",
//     designationId: 2,
//     designationName: "Senior Executive",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Married",
//     dob: "1982-07-30",
//     joinDate: "2021-12-05",
//     phoneNo: "+971-50-345-6789",
//     offEmailAdd: "badrudin.glandel@company.com",
//     bankName: "Noor Bank",
//     accountNo: "AE345678901234567890123",
//     nationality: "Filipino",
//     emiratesIDNo: "784-1982-3456789-0",
//     emiratesIDExpiry: "2026-02-28",
//     isActive: true,
//     createDate: "2021-12-05",
//     createBy: "admin",
//   },
//   {
//     employeeId: 14,
//     companyId: 1,
//     code: "EMP0014",
//     employeeName: "Ruver Anthony Anoche",
//     departmentId: 7,
//     departmentName: "Marketing",
//     designationId: 3,
//     designationName: "Coordinator",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Single",
//     dob: "1991-03-25",
//     joinDate: "2022-05-12",
//     phoneNo: "+971-50-456-7890",
//     offEmailAdd: "ruver.anoche@company.com",
//     bankName: "Bank of Sharjah",
//     accountNo: "AE456789012345678901234",
//     nationality: "Filipino",
//     emiratesIDNo: "784-1991-4567890-1",
//     emiratesIDExpiry: "2027-08-10",
//     isActive: true,
//     createDate: "2022-05-12",
//     createBy: "admin",
//   },
//   {
//     employeeId: 15,
//     companyId: 1,
//     code: "EMP0015",
//     employeeName: "Jesus Abon Abus",
//     departmentId: 8,
//     departmentName: "Customer Service",
//     designationId: 4,
//     designationName: "Coordinator",
//     genderId: 1,
//     genderName: "Male",
//     martialStatus: "Married",
//     dob: "1988-11-15",
//     joinDate: "2021-07-18",
//     phoneNo: "+971-50-567-8901",
//     offEmailAdd: "jesus.abus@company.com",
//     bankName: "Commercial Bank International",
//     accountNo: "AE567890123456789012345",
//     nationality: "Filipino",
//     emiratesIDNo: "784-1988-5678901-2",
//     emiratesIDExpiry: "2026-09-25",
//     isActive: true,
//     createDate: "2021-07-18",
//     createBy: "admin",
//   },
// ]

// // Dummy Payroll Components
// export const dummyPayrollComponents: IPayrollComponent[] = [
//   {
//     payrollComponentId: 1,
//     companyId: 1,
//     componentCode: "BASIC",
//     componentName: "Basic Salary",
//     componentType: "EARNING",
//     isTaxable: true,
//     isOvertime: false,
//     isBonus: false,
//     isCommission: false,
//     isLeave: false,
//     isLate: false,
//     isSocialInsurance: false,
//     calculationType: "FIXED",
//     calculationValue: 0,
//     sortOrder: 1,
//     isActive: true,
//     createDate: "2024-01-01",
//     createBy: "admin",
//   },
//   {
//     payrollComponentId: 2,
//     companyId: 1,
//     componentCode: "HOUSING",
//     componentName: "Housing Allowance",
//     componentType: "EARNING",
//     isTaxable: false,
//     isOvertime: false,
//     isBonus: false,
//     isCommission: false,
//     isLeave: false,
//     isLate: false,
//     isSocialInsurance: false,
//     calculationType: "PERCENTAGE",
//     calculationValue: 25,
//     sortOrder: 2,
//     isActive: true,
//     createDate: "2024-01-01",
//     createBy: "admin",
//   },
//   {
//     payrollComponentId: 3,
//     companyId: 1,
//     componentCode: "TRANSPORT",
//     componentName: "Transport Allowance",
//     componentType: "EARNING",
//     isTaxable: false,
//     isOvertime: false,
//     isBonus: false,
//     isCommission: false,
//     isLeave: false,
//     isLate: false,
//     isSocialInsurance: false,
//     calculationType: "FIXED",
//     calculationValue: 500,
//     sortOrder: 3,
//     isActive: true,
//     createDate: "2024-01-01",
//     createBy: "admin",
//   },
//   {
//     payrollComponentId: 4,
//     companyId: 1,
//     componentCode: "OVERTIME",
//     componentName: "Overtime Pay",
//     componentType: "EARNING",
//     isTaxable: true,
//     isOvertime: true,
//     isBonus: false,
//     isCommission: false,
//     isLeave: false,
//     isLate: false,
//     isSocialInsurance: false,
//     calculationType: "FORMULA",
//     calculationFormula: "BASIC * 1.5 * OVERTIME_HOURS / 160",
//     sortOrder: 4,
//     isActive: true,
//     createDate: "2024-01-01",
//     createBy: "admin",
//   },
//   {
//     payrollComponentId: 5,
//     companyId: 1,
//     componentCode: "BONUS",
//     componentName: "Performance Bonus",
//     componentType: "EARNING",
//     isTaxable: true,
//     isOvertime: false,
//     isBonus: true,
//     isCommission: false,
//     isLeave: false,
//     isLate: false,
//     isSocialInsurance: false,
//     calculationType: "PERCENTAGE",
//     calculationValue: 10,
//     sortOrder: 5,
//     isActive: true,
//     createDate: "2024-01-01",
//     createBy: "admin",
//   },
//   {
//     payrollComponentId: 6,
//     companyId: 1,
//     componentCode: "SOCIAL_INS",
//     componentName: "Social Insurance",
//     componentType: "DEDUCTION",
//     isTaxable: false,
//     isOvertime: false,
//     isBonus: false,
//     isCommission: false,
//     isLeave: false,
//     isLate: false,
//     isSocialInsurance: true,
//     calculationType: "PERCENTAGE",
//     calculationValue: 5,
//     sortOrder: 6,
//     isActive: true,
//     createDate: "2024-01-01",
//     createBy: "admin",
//   },
//   {
//     payrollComponentId: 7,
//     companyId: 1,
//     componentCode: "LATE_DED",
//     componentName: "Late Deduction",
//     componentType: "DEDUCTION",
//     isTaxable: false,
//     isOvertime: false,
//     isBonus: false,
//     isCommission: false,
//     isLeave: false,
//     isLate: true,
//     isSocialInsurance: false,
//     calculationType: "FIXED",
//     calculationValue: 50,
//     sortOrder: 7,
//     isActive: true,
//     createDate: "2024-01-01",
//     createBy: "admin",
//   },
// ]

// // Dummy Payroll Employee Data (for current month)
// export const dummyPayrollEmployees: IPayrollEmployee[] = [
//   {
//     payrollEmployeeId: 1,
//     employeeId: 1,
//     employeeCode: "EMP001",
//     employeeName: "George K. Thomas",
//     departmentName: "IT Department",
//     payrollPeriodId: 1,
//     periodName: "January 2024",
//     basicSalary: 8000,
//     housingAllowance: 2000,
//     transportAllowance: 500,
//     otherAllowances: 300,
//     totalEarnings: 10800,
//     socialInsurance: 400,
//     otherDeductions: 0,
//     totalDeductions: 400,
//     netSalary: 10400,
//     overtimeHours: 8,
//     overtimeRate: 75,
//     overtimeAmount: 600,
//     bonusAmount: 800,
//     commissionAmount: 0,
//     leaveDeduction: 150,
//     lateDeduction: 0,
//     otherEarnings: 0,
//     isProcessed: true,
//     processedDate: "2024-01-31",
//     processedBy: "admin",
//     isPaid: true,
//     paidDate: "2024-02-01",
//     paidBy: "admin",
//     paymentMethod: "Bank Transfer",
//     bankTransferRef: "BT-2024-001",
//     createDate: "2024-01-31",
//     createBy: "admin",
//   },
//   {
//     payrollEmployeeId: 2,
//     companyId: 1,
//     employeeId: 2,
//     employeeCode: "EMP002",
//     employeeName: "Jayasankar C.",
//     departmentName: "Finance",
//     payrollPeriodId: 1,
//     periodName: "January 2024",
//     basicSalary: 6000,
//     housingAllowance: 1500,
//     transportAllowance: 500,
//     otherAllowances: 200,
//     totalEarnings: 8200,
//     socialInsurance: 300,
//     otherDeductions: 0,
//     totalDeductions: 300,
//     netSalary: 7900,
//     overtimeHours: 5,
//     overtimeRate: 56.25,
//     overtimeAmount: 281.25,
//     bonusAmount: 600,
//     commissionAmount: 0,
//     leaveDeduction: 300,
//     lateDeduction: 0,
//     otherEarnings: 0,
//     isProcessed: true,
//     processedDate: "2024-01-31",
//     processedBy: "admin",
//     isPaid: true,
//     paidDate: "2024-02-01",
//     paidBy: "admin",
//     paymentMethod: "Bank Transfer",
//     bankTransferRef: "BT-2024-002",
//     createDate: "2024-01-31",
//     createBy: "admin",
//   },
//   {
//     payrollEmployeeId: 3,
//     companyId: 1,
//     employeeId: 3,
//     employeeCode: "EMP003",
//     employeeName: "Sonia Seloveres",
//     departmentName: "HR",
//     payrollPeriodId: 1,
//     periodName: "January 2024",
//     basicSalary: 7000,
//     housingAllowance: 1750,
//     transportAllowance: 500,
//     otherAllowances: 250,
//     totalEarnings: 9500,
//     socialInsurance: 350,
//     otherDeductions: 0,
//     totalDeductions: 350,
//     netSalary: 9150,
//     overtimeHours: 3,
//     overtimeRate: 65.625,
//     overtimeAmount: 196.88,
//     bonusAmount: 700,
//     commissionAmount: 0,
//     leaveDeduction: 250,
//     lateDeduction: 0,
//     otherEarnings: 0,
//     isProcessed: true,
//     processedDate: "2024-01-31",
//     processedBy: "admin",
//     isPaid: true,
//     paidDate: "2024-02-01",
//     paidBy: "admin",
//     paymentMethod: "Bank Transfer",
//     bankTransferRef: "BT-2024-003",
//     createDate: "2024-01-31",
//     createBy: "admin",
//   },
//   {
//     payrollEmployeeId: 4,
//     companyId: 1,
//     employeeId: 4,
//     employeeCode: "EMP004",
//     employeeName: "Shamaj E. Vasu",
//     departmentName: "IT Department",
//     payrollPeriodId: 1,
//     periodName: "January 2024",
//     basicSalary: 5000,
//     housingAllowance: 1250,
//     transportAllowance: 500,
//     otherAllowances: 150,
//     totalEarnings: 6900,
//     socialInsurance: 250,
//     otherDeductions: 0,
//     totalDeductions: 250,
//     netSalary: 6650,
//     overtimeHours: 12,
//     overtimeRate: 46.875,
//     overtimeAmount: 562.5,
//     bonusAmount: 500,
//     commissionAmount: 0,
//     leaveDeduction: 400,
//     lateDeduction: 0,
//     otherEarnings: 0,
//     isProcessed: true,
//     processedDate: "2024-01-31",
//     processedBy: "admin",
//     isPaid: true,
//     paidDate: "2024-02-01",
//     paidBy: "admin",
//     paymentMethod: "Bank Transfer",
//     bankTransferRef: "BT-2024-004",
//     createDate: "2024-01-31",
//     createBy: "admin",
//   },
//   {
//     payrollEmployeeId: 5,
//     companyId: 1,
//     employeeId: 5,
//     employeeCode: "EMP005",
//     employeeName: "Priyesh T.V.",
//     departmentName: "Operations",
//     payrollPeriodId: 1,
//     periodName: "January 2024",
//     basicSalary: 6500,
//     housingAllowance: 1625,
//     transportAllowance: 500,
//     otherAllowances: 200,
//     totalEarnings: 8825,
//     socialInsurance: 325,
//     otherDeductions: 0,
//     totalDeductions: 325,
//     netSalary: 8500,
//     overtimeHours: 6,
//     overtimeRate: 60.94,
//     overtimeAmount: 365.63,
//     bonusAmount: 650,
//     commissionAmount: 0,
//     leaveDeduction: 180,
//     lateDeduction: 0,
//     otherEarnings: 0,
//     isProcessed: true,
//     processedDate: "2024-01-31",
//     processedBy: "admin",
//     isPaid: true,
//     paidDate: "2024-02-01",
//     paidBy: "admin",
//     paymentMethod: "Bank Transfer",
//     bankTransferRef: "BT-2024-005",
//     createDate: "2024-01-31",
//     createBy: "admin",
//   },
// ]

// // Helper function to generate payroll data for all employees
// export const generatePayrollDataForAllEmployees = (): IPayrollEmployee[] => {
//   return dummyEmployees.map((employee, index) => {
//     const basicSalary = 4000 + index * 300 // Varying basic salaries
//     const housingAllowance = basicSalary * 0.25
//     const transportAllowance = 500
//     const otherAllowances = 150 + index * 10
//     const totalEarnings =
//       basicSalary + housingAllowance + transportAllowance + otherAllowances
//     const socialInsurance = basicSalary * 0.05
//     const totalDeductions = socialInsurance
//     const netSalary = totalEarnings - totalDeductions
//     const overtimeHours = Math.floor(Math.random() * 15) + 1
//     const overtimeRate = (basicSalary * 1.5) / 160
//     const overtimeAmount = overtimeHours * overtimeRate
//     const bonusAmount = basicSalary * 0.1
//     const leaveDeduction =
//       Math.random() > 0.7 ? Math.floor(Math.random() * 500) + 100 : 0 // 30% chance of leave deduction

//     return {
//       payrollEmployeeId: index + 1,
//       companyId: 1,
//       employeeId: employee.employeeId,
//       employeeCode: employee.code,
//       employeeName: employee.employeeName,
//       departmentName: employee.departmentName,
//       payrollPeriodId: 1,
//       periodName: "January 2024",
//       basicSalary,
//       housingAllowance,
//       transportAllowance,
//       otherAllowances,
//       totalEarnings,
//       socialInsurance,
//       otherDeductions: 0,
//       totalDeductions,
//       netSalary,
//       overtimeHours,
//       overtimeRate,
//       overtimeAmount,
//       bonusAmount,
//       commissionAmount: 0,
//       leaveDeduction,
//       lateDeduction: 0,
//       otherEarnings: 0,
//       isProcessed: true,
//       processedDate: "2024-01-31",
//       processedBy: "admin",
//       isPaid: true,
//       paidDate: "2024-02-01",
//       paidBy: "admin",
//       paymentMethod: "Bank Transfer",
//       bankTransferRef: `BT-2024-${String(index + 1).padStart(3, "0")}`,
//       createDate: "2024-01-31",
//       createBy: "admin",
//     }
//   })
// }
