import {
  ILoan,
  ILoanApplication,
  ILoanApproval,
  ILoanDashboard,
  ILoanRepayment,
} from "@/interfaces/loan"

// Dummy Loan Applications
export const dummyLoanApplications: ILoanApplication[] = [
  {
    applicationId: 1,
    employeeId: 1,
    employeeName: "George K. Thomas",
    employeeCode: "EMP001",
    departmentName: "IT Department",
    designationName: "Manager",
    loanType: "Housing",
    requestedAmount: 50000,
    purpose:
      "To purchase a new apartment in Dubai Marina. Need funds for down payment and initial setup costs.",
    repaymentPeriod: 60,
    monthlyIncome: 12000,
    existingLoans: 0,
    applicationDate: new Date("2024-01-15"),
    status: "Approved",
    submittedDate: new Date("2024-01-15"),
    reviewedBy: 2,
    reviewedByName: "Jayasankar C.",
    reviewedDate: new Date("2024-01-18"),
    approvedBy: 2,
    approvedByName: "Jayasankar C.",
    approvedDate: new Date("2024-01-20"),
    remarks: "Approved with standard terms",
    createDate: new Date("2024-01-15"),
    createBy: "George K. Thomas",
  },
  {
    applicationId: 2,
    employeeId: 3,
    employeeName: "Sonia Seloveres",
    employeeCode: "EMP003",
    departmentName: "HR",
    designationName: "Senior Executive",
    loanType: "Vehicle",
    requestedAmount: 25000,
    purpose:
      "To purchase a new car for daily commute. Current vehicle is old and requires frequent repairs.",
    repaymentPeriod: 36,
    monthlyIncome: 9500,
    existingLoans: 0,
    applicationDate: new Date("2024-01-20"),
    status: "Under Review",
    submittedDate: new Date("2024-01-20"),
    reviewedBy: 2,
    reviewedByName: "Jayasankar C.",
    reviewedDate: new Date("2024-01-22"),
    remarks: "Under review for vehicle loan",
    createDate: new Date("2024-01-20"),
    createBy: "Sonia Seloveres",
  },
  {
    applicationId: 3,
    employeeId: 5,
    employeeName: "Priyesh T.V.",
    employeeCode: "EMP005",
    departmentName: "Operations",
    designationName: "Senior Executive",
    loanType: "Personal",
    requestedAmount: 15000,
    purpose:
      "Emergency medical expenses for family member. Need funds for surgery and treatment.",
    repaymentPeriod: 24,
    monthlyIncome: 8500,
    existingLoans: 5000,
    applicationDate: new Date("2024-01-25"),
    status: "Submitted",
    submittedDate: new Date("2024-01-25"),
    remarks: "Emergency personal loan request",
    createDate: new Date("2024-01-25"),
    createBy: "Priyesh T.V.",
  },
  {
    applicationId: 4,
    employeeId: 7,
    employeeName: "Gijo Thomas",
    employeeCode: "EMP007",
    departmentName: "Finance",
    designationName: "Accountant",
    loanType: "Education",
    requestedAmount: 30000,
    purpose:
      "To pursue MBA degree from a recognized university. This will help in career advancement.",
    repaymentPeriod: 48,
    monthlyIncome: 7000,
    existingLoans: 0,
    applicationDate: new Date("2024-01-28"),
    status: "Draft",
    remarks: "Education loan for MBA",
    createDate: new Date("2024-01-28"),
    createBy: "Gijo Thomas",
  },
  {
    applicationId: 5,
    employeeId: 2,
    employeeName: "Jayasankar C.",
    employeeCode: "EMP002",
    departmentName: "Finance",
    designationName: "Senior Executive",
    loanType: "Housing",
    requestedAmount: 75000,
    purpose:
      "To renovate and expand current home. Need additional space for growing family.",
    repaymentPeriod: 72,
    monthlyIncome: 10000,
    existingLoans: 20000,
    applicationDate: new Date("2024-02-01"),
    status: "Rejected",
    submittedDate: new Date("2024-02-01"),
    reviewedBy: 1,
    reviewedByName: "George K. Thomas",
    reviewedDate: new Date("2024-02-03"),
    approvedBy: 1,
    approvedByName: "George K. Thomas",
    approvedDate: new Date("2024-02-03"),
    rejectionReason:
      "Loan amount exceeds maximum limit for existing loan holders. Consider reducing amount or clearing existing loan first.",
    remarks: "Rejected due to existing loan balance",
    createDate: new Date("2024-02-01"),
    createBy: "Jayasankar C.",
  },
]

// Dummy Loans (approved applications converted to loans)
export const dummyLoans: ILoan[] = [
  {
    loanId: 1,
    employeeId: 1,
    employeeName: "George K. Thomas",
    employeeCode: "EMP001",
    departmentName: "IT Department",
    designationName: "Manager",
    loanType: "Housing",
    loanAmount: 50000,
    loanDate: new Date("2024-01-25"),
    interestRate: 8.5,
    repaymentTerms: "60 months, monthly payments",
    monthlyPayment: 1025.5,
    totalPayable: 61530,
    status: "Active",
    approvedBy: 2,
    approvedByName: "Jayasankar C.",
    approvedDate: new Date("2024-01-20"),
    remarks: "Housing loan for apartment purchase",
    createDate: new Date("2024-01-25"),
    createBy: "admin",
  },
  {
    loanId: 2,
    employeeId: 4,
    employeeName: "Shamaj E. Vasu",
    employeeCode: "EMP004",
    departmentName: "IT Department",
    designationName: "Developer",
    loanType: "Personal",
    loanAmount: 20000,
    loanDate: new Date("2023-11-15"),
    interestRate: 10.0,
    repaymentTerms: "36 months, monthly payments",
    monthlyPayment: 645.5,
    totalPayable: 23238,
    status: "Active",
    approvedBy: 2,
    approvedByName: "Jayasankar C.",
    approvedDate: new Date("2023-11-10"),
    remarks: "Personal loan for home renovation",
    createDate: new Date("2023-11-15"),
    createBy: "admin",
  },
  {
    loanId: 3,
    employeeId: 6,
    employeeName: "Babu Unni M",
    employeeCode: "EMP006",
    departmentName: "Logistics",
    designationName: "Coordinator",
    loanType: "Vehicle",
    loanAmount: 30000,
    loanDate: new Date("2023-09-20"),
    interestRate: 9.0,
    repaymentTerms: "48 months, monthly payments",
    monthlyPayment: 747.5,
    totalPayable: 35880,
    status: "Active",
    approvedBy: 2,
    approvedByName: "Jayasankar C.",
    approvedDate: new Date("2023-09-15"),
    remarks: "Vehicle loan for new car",
    createDate: new Date("2023-09-20"),
    createBy: "admin",
  },
  {
    loanId: 4,
    employeeId: 8,
    employeeName: "Mohammed Akbar",
    employeeCode: "EMP008",
    departmentName: "Sales",
    designationName: "Senior Executive",
    loanType: "Education",
    loanAmount: 40000,
    loanDate: new Date("2023-06-10"),
    interestRate: 7.5,
    repaymentTerms: "60 months, monthly payments",
    monthlyPayment: 802.0,
    totalPayable: 48120,
    status: "Active",
    approvedBy: 2,
    approvedByName: "Jayasankar C.",
    approvedDate: new Date("2023-06-05"),
    remarks: "Education loan for professional certification",
    createDate: new Date("2023-06-10"),
    createBy: "admin",
  },
  {
    loanId: 5,
    employeeId: 10,
    employeeName: "Vyas M.V.",
    employeeCode: "EMP0010",
    departmentName: "HR",
    designationName: "Coordinator",
    loanType: "Emergency",
    loanAmount: 15000,
    loanDate: new Date("2023-12-05"),
    interestRate: 12.0,
    repaymentTerms: "24 months, monthly payments",
    monthlyPayment: 706.25,
    totalPayable: 16950,
    status: "Active",
    approvedBy: 2,
    approvedByName: "Jayasankar C.",
    approvedDate: new Date("2023-12-01"),
    remarks: "Emergency loan for medical expenses",
    createDate: new Date("2023-12-05"),
    createBy: "admin",
  },
]

// Dummy Loan Repayments
export const dummyLoanRepayments: ILoanRepayment[] = [
  {
    repaymentId: 1,
    loanId: 1,
    employeeId: 1,
    employeeName: "George K. Thomas",
    employeeCode: "EMP001",
    loanType: "Housing",
    paymentDate: new Date("2024-02-01"),
    paymentAmount: 1025.5,
    principalAmount: 750.0,
    interestAmount: 275.5,
    remainingBalance: 49250.0,
    paymentMethod: "Salary Deduction",
    referenceNumber: "SD-2024-001",
    remarks: "First monthly payment",
    createDate: new Date("2024-02-01"),
    createBy: "admin",
  },
  {
    repaymentId: 2,
    loanId: 2,
    employeeId: 4,
    employeeName: "Shamaj E. Vasu",
    employeeCode: "EMP004",
    loanType: "Personal",
    paymentDate: new Date("2024-02-01"),
    paymentAmount: 645.5,
    principalAmount: 500.0,
    interestAmount: 145.5,
    remainingBalance: 18500.0,
    paymentMethod: "Salary Deduction",
    referenceNumber: "SD-2024-002",
    remarks: "Monthly payment",
    createDate: new Date("2024-02-01"),
    createBy: "admin",
  },
  {
    repaymentId: 3,
    loanId: 3,
    employeeId: 6,
    employeeName: "Babu Unni M",
    employeeCode: "EMP006",
    loanType: "Vehicle",
    paymentDate: new Date("2024-02-01"),
    paymentAmount: 747.5,
    principalAmount: 550.0,
    interestAmount: 197.5,
    remainingBalance: 26450.0,
    paymentMethod: "Salary Deduction",
    referenceNumber: "SD-2024-003",
    remarks: "Monthly payment",
    createDate: new Date("2024-02-01"),
    createBy: "admin",
  },
  {
    repaymentId: 4,
    loanId: 4,
    employeeId: 8,
    employeeName: "Mohammed Akbar",
    employeeCode: "EMP008",
    loanType: "Education",
    paymentDate: new Date("2024-02-01"),
    paymentAmount: 802.0,
    principalAmount: 600.0,
    interestAmount: 202.0,
    remainingBalance: 35200.0,
    paymentMethod: "Salary Deduction",
    referenceNumber: "SD-2024-004",
    remarks: "Monthly payment",
    createDate: new Date("2024-02-01"),
    createBy: "admin",
  },
  {
    repaymentId: 5,
    loanId: 5,
    employeeId: 10,
    employeeName: "Vyas M.V.",
    employeeCode: "EMP0010",
    loanType: "Emergency",
    paymentDate: new Date("2024-02-01"),
    paymentAmount: 706.25,
    principalAmount: 550.0,
    interestAmount: 156.25,
    remainingBalance: 13450.0,
    paymentMethod: "Salary Deduction",
    referenceNumber: "SD-2024-005",
    remarks: "Monthly payment",
    createDate: new Date("2024-02-01"),
    createBy: "admin",
  },
  {
    repaymentId: 6,
    loanId: 2,
    employeeId: 4,
    employeeName: "Shamaj E. Vasu",
    employeeCode: "EMP004",
    loanType: "Personal",
    paymentDate: new Date("2024-01-15"),
    paymentAmount: 645.5,
    principalAmount: 500.0,
    interestAmount: 145.5,
    remainingBalance: 19000.0,
    paymentMethod: "Salary Deduction",
    referenceNumber: "SD-2024-006",
    remarks: "Monthly payment",
    createDate: new Date("2024-01-15"),
    createBy: "admin",
  },
  {
    repaymentId: 7,
    loanId: 3,
    employeeId: 6,
    employeeName: "Babu Unni M",
    employeeCode: "EMP006",
    loanType: "Vehicle",
    paymentDate: new Date("2024-01-15"),
    paymentAmount: 747.5,
    principalAmount: 550.0,
    interestAmount: 197.5,
    remainingBalance: 27000.0,
    paymentMethod: "Salary Deduction",
    referenceNumber: "SD-2024-007",
    remarks: "Monthly payment",
    createDate: new Date("2024-01-15"),
    createBy: "admin",
  },
]

// Dummy Loan Approvals
export const dummyLoanApprovals: ILoanApproval[] = [
  {
    approvalId: 1,
    applicationId: 1,
    employeeName: "George K. Thomas",
    employeeCode: "EMP001",
    loanType: "Housing",
    requestedAmount: 50000,
    approverId: 2,
    approverName: "Jayasankar C.",
    approvalStatus: "Approved",
    approvalDate: new Date("2024-01-20"),
    approvedAmount: 50000,
    approvedInterestRate: 8.5,
    approvedRepaymentPeriod: 60,
    remarks: "Approved with standard housing loan terms",
    createDate: new Date("2024-01-20"),
    createBy: "Jayasankar C.",
  },
  {
    approvalId: 2,
    applicationId: 5,
    employeeName: "Jayasankar C.",
    employeeCode: "EMP002",
    loanType: "Housing",
    requestedAmount: 75000,
    approverId: 1,
    approverName: "George K. Thomas",
    approvalStatus: "Rejected",
    approvalDate: new Date("2024-02-03"),
    rejectionReason:
      "Loan amount exceeds maximum limit for existing loan holders. Consider reducing amount or clearing existing loan first.",
    remarks: "Rejected due to existing loan balance",
    createDate: new Date("2024-02-03"),
    createBy: "George K. Thomas",
  },
]

// Dummy Loan Dashboard Data
export const dummyLoanDashboard: ILoanDashboard = {
  totalLoans: 5,
  activeLoans: 5,
  pendingApplications: 2,
  totalLoanAmount: 150000,
  totalOutstandingAmount: 132450,
  monthlyRepayments: 3926.75,
  overdueLoans: 0,
  recentApplications: dummyLoanApplications.slice(0, 3),
  recentRepayments: dummyLoanRepayments.slice(0, 5),
}

// Helper function to calculate loan statistics
export const calculateLoanStatistics = () => {
  const totalLoans = dummyLoans.length
  const activeLoans = dummyLoans.filter(
    (loan) => loan.status === "Active"
  ).length
  const pendingApplications = dummyLoanApplications.filter(
    (app) => app.status === "Submitted" || app.status === "Under Review"
  ).length
  const totalLoanAmount = dummyLoans.reduce(
    (sum, loan) => sum + loan.loanAmount,
    0
  )
  const totalOutstandingAmount = dummyLoans.reduce((sum, loan) => {
    const repayments = dummyLoanRepayments.filter(
      (rep) => rep.loanId === loan.loanId
    )
    const totalPaid = repayments.reduce(
      (paid, rep) => paid + rep.principalAmount,
      0
    )
    return sum + (loan.loanAmount - totalPaid)
  }, 0)
  const monthlyRepayments = dummyLoanRepayments
    .filter((rep) => rep.paymentDate.getMonth() === new Date().getMonth())
    .reduce((sum, rep) => sum + rep.paymentAmount, 0)

  return {
    totalLoans,
    activeLoans,
    pendingApplications,
    totalLoanAmount,
    totalOutstandingAmount,
    monthlyRepayments,
    overdueLoans: 0,
  }
}
